import type { Metadata } from 'next';

import '../globals.css';

export const metadata: Metadata = {
  title: 'Carptravel Studio',
  description: 'Generated by Next.js & Sanity',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
